import Head from 'next/head';
import styled from '@emotion/styled';
import axios from 'axios';
import { useState } from 'react';

import NavBar from '../components/NavBar';
import { Box } from '@chakra-ui/react';

const StyledHome = styled.div`
  .container {
    width: 1200px;
    margin: 0 auto;
    padding: 1rem;
  }
`;

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState({});

  const fetchResult = async (title) => {
    setLoading(true);
    try {
      const response = await axios.get(`http://127.0.0.1:5000/${title}`);
      console.log(response);
      setAnalysis(response.data);
    } catch (err) {
      console.log(err);
    }
    setLoading(false);
  };

  return (
    <StyledHome>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <Box className="container">
          <Box>
            Hi there, this is the final project for the class Audio Processing
            and Indexing. This project is a music analyzer utilizing the Python
            library &quot;librosa&quot; to do feature extraction.
          </Box>
        </Box>
      </main>

      <footer></footer>
    </StyledHome>
  );
};

export default Home;
